# Generated by Django 5.2.3 on 2025-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file (PDF, image, etc.)', upload_to='uploads/%Y/%m/%d/')),
                ('qr_code', models.FileField(blank=True, help_text='QR code image for the file', upload_to='qrcodes/%Y/%m/%d/')),
            ],
        ),
    ]
